///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace dataTableWrite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the dataTableWriteRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("e21d1845-91b7-41e6-b24e-98dd25334cf8")]
    public partial class dataTableWriteRepository : RepoGenBaseFolder
    {
        static dataTableWriteRepository instance = new dataTableWriteRepository();

        /// <summary>
        /// Gets the singleton class instance representing the dataTableWriteRepository element repository.
        /// </summary>
        [RepositoryFolder("e21d1845-91b7-41e6-b24e-98dd25334cf8")]
        public static dataTableWriteRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public dataTableWriteRepository() 
            : base("dataTableWriteRepository", "/", null, 0, false, "e21d1845-91b7-41e6-b24e-98dd25334cf8", ".\\RepositoryImages\\dataTableWriteRepositorye21d1845.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e21d1845-91b7-41e6-b24e-98dd25334cf8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class dataTableWriteRepositoryFolders
    {
    }
#pragma warning restore 0436
}